stages:
- build

before_script:
  - uname -a
  - whoami
  - echo $LANG
  - g++ --version
  - clang++ --version
  - mkdir build
  - cd build

build:fedora:
  stage: build
  image: biboumi-test-fedora:latest
  script:
    - cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug -DWITH_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITH_LIBIDN=1 -DWITH_LITESQL=1
    - make biboumi -j$(nproc)
    - make coverage -j$(nproc)
    - make check -j$(nproc)
    - mkdir tests_outputs && pushd tests_outputs && make e2e -j$(nproc) -C .. && popd
    - make rpm -j$(nproc)
  artifacts:
    paths:
      - build/coverage/
      - build/rpmbuild/RPMS
      - build/rpmbuild/SRPMS
      - build/tests_outputs/
    when: always

build:debian:
  stage: build
  image: biboumi-test-debian:latest
  script:
    - cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug -DWITH_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITH_LIBIDN=1 -DWITH_LITESQL=1
    - make biboumi -j$(nproc)
    - make coverage -j$(nproc)
    - make check -j$(nproc)
    - mkdir tests_outputs && pushd tests_outputs && make e2e -j$(nproc) -C .. && popd
  artifacts:
    paths:
      - build/coverage/
      - build/tests_outputs/
    when: always
