stages:
- build

before_script:
  - uname -a
  - whoami
  - echo $LANG
  - g++ --version
  - clang++ --version

build:
  stage: build
  script:
    - whoami
    - echo $LANG
    - echo $PATH
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug -DWITH_BOTAN=1 -DWITH_CARES=1 -DWITH_SYSTEMD=1 -DWITH_LIBIDN=1 -DWITH_LITESQL=1
    - make biboumi -j$(nproc)
    - make coverage -j$(nproc)
    - make check -j$(nproc)
    - make rpm -j$(nproc)
  artifacts:
    paths:
      - build/




