stages:
  - packaging # Publish some packages (rpm, deb…)

before_script:
  - uname -a
  - whoami
  - mkdir -p build/
  - cd build/

packaging:deb:
  stage: packaging
  only:
    - master@louiz/biboumi
    - debian@louiz/biboumi
  tags:
    - docker
  image: docker.louiz.org/packaging-debian:latest
  before_script: []
  script:
    - git checkout debian
    - git merge --no-commit --no-ff master
    - mk-build-deps
    - apt update -y
    - apt install -y ./biboumi-build-deps*.deb
    - debuild -b -us -uc
    - mv ../*.deb .
    - mv ../*.build .
    - mv ../*.buildinfo .
  dependencies: []
  artifacts:
    untracked: true
    name: $CI_PROJECT_NAME-deb-$CI_BUILD_ID
